# Generated by Django 3.1.7 on 2021-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='error_codes',
            field=models.ManyToManyField(null=True, to='product.ErrorCodesForProduct'),
        ),
    ]
