# Generated by Django 3.1.7 on 2021-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210320_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='error_codes',
            field=models.ManyToManyField(blank=True, to='product.ErrorCodesForProduct'),
        ),
    ]
