# Generated by Django 3.1.7 on 2021-03-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210320_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_no',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
